project_id = "kuer-studio"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[local_smtp]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "10MiB"

[storage.buckets.qr-assets]
public = true
file_size_limit = "10MiB"
allowed_mime_types = ["image/png", "image/jpeg", "image/webp", "image/svg+xml"]

[auth]
enabled = true
site_url = "https://studio.mnrv.nl"
additional_redirect_urls = ["https://studio.mnrv.nl/auth/callback", "http://localhost:3000/auth/callback", "http://127.0.0.1:3000/auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.rate_limit]
email_sent = 2
sms_sent = 30
anonymous_users = 0
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30
web3 = 0

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = true
max_frequency = "60s"
otp_length = 6
otp_expiry = 900

[auth.sms]
enable_signup = false
enable_confirmations = false
