import type { QrMode, QrModeId } from '@/types/qrModes'

export const QR_MODES: Record<QrModeId, QrMode> = {
  brand: {
    id: 'brand',
    name: 'Brand QR',
    description: 'Corporate branding with logo integration and brand colors',
    icon: 'Briefcase',
    defaultModel: 'qr-monster-v2',
    promptStrategy: 'vision-guided',
    parameterPresets: {
      controlWeight: 1.0,
      guidanceScale: 8,
      strength: 0.82,
      conditioningScale: 1.8,
      numInferenceSteps: 35,
    },
    styleVariations: [
      { id: 'brand-corporate', name: 'Corporate Clean', presetId: 'corporate-clean', prompt: 'Professional corporate branded QR code, clean lines, trustworthy blue tones, business-appropriate', previewColors: ['#1e3a5f', '#4a90d9', '#ffffff'] },
      { id: 'brand-luxury', name: 'Premium Luxury', presetId: 'premium-luxury', prompt: 'Luxury branded QR with gold accents, deep navy, elegant serif typography areas', previewColors: ['#1a1a2e', '#d4af37', '#0f0f1a'] },
      { id: 'brand-minimal', name: 'Minimal', presetId: 'minimal-editorial', prompt: 'Minimal branded QR, Swiss grid, clean monochrome with single brand accent', previewColors: ['#fafafa', '#333333', '#e0e0e0'] },
      { id: 'brand-bold', name: 'Bold Statement', prompt: 'Bold branded QR with strong color blocks, geometric brand shapes, high impact', previewColors: ['#ff3b30', '#000000', '#ffffff'] },
    ],
    requiredInputs: ['brand-kit'],
    optionalInputs: ['logo', 'image'],
    scanStrictness: 'strict',
  },
  character: {
    id: 'character',
    name: 'Character QR',
    description: 'Portraits and characters integrated with QR structure',
    icon: 'User',
    defaultModel: 'qr-monster-v2',
    promptStrategy: 'llm-generated',
    parameterPresets: {
      controlWeight: 0.85,
      guidanceScale: 7.5,
      strength: 0.88,
      conditioningScale: 1.5,
      numInferenceSteps: 35,
    },
    styleVariations: [
      { id: 'char-anime', name: 'Anime Style', prompt: 'Anime character portrait, QR matrix as hair or clothing texture, vibrant colors, cel-shaded', previewColors: ['#ff6b9d', '#c44569', '#2d2d2d'] },
      { id: 'char-realistic', name: 'Photorealistic', prompt: 'Photorealistic portrait, QR modules as skin texture or facial geometry, studio lighting', previewColors: ['#d4a574', '#8b6914', '#2c1810'] },
      { id: 'char-comic', name: 'Comic Book', prompt: 'Comic book hero portrait, QR pattern as bold halftone dots, dynamic pose, action lines', previewColors: ['#e63946', '#457b9d', '#f1faee'] },
      { id: 'char-fantasy', name: 'Fantasy', prompt: 'Fantasy character portrait, QR as magical runes or enchanted patterns, ethereal glow', previewColors: ['#6c63ff', '#3d3d8f', '#e0d6ff'] },
    ],
    requiredInputs: [],
    optionalInputs: ['image', 'text'],
    scanStrictness: 'moderate',
  },
  product: {
    id: 'product',
    name: 'Product QR',
    description: 'Product photography with seamlessly embedded QR',
    icon: 'Package',
    defaultModel: 'qr-monster-v2',
    promptStrategy: 'vision-guided',
    parameterPresets: {
      controlWeight: 1.0,
      guidanceScale: 8,
      strength: 0.8,
      conditioningScale: 1.8,
      numInferenceSteps: 32,
    },
    styleVariations: [
      { id: 'prod-packaging', name: 'Packaging', presetId: 'product-packaging', prompt: 'Clean product packaging QR, print-safe colors, professional branding, shelf-ready', previewColors: ['#f8f4ef', '#2d3436', '#e17055'] },
      { id: 'prod-lifestyle', name: 'Lifestyle', prompt: 'Lifestyle product shot with embedded QR, warm natural lighting, aspirational mood', previewColors: ['#f5e6d3', '#8b7355', '#2c2c2c'] },
      { id: 'prod-tech', name: 'Tech Product', presetId: 'tech-circuitboard', prompt: 'Tech product with circuitboard QR integration, sleek metallic, blue-grey tones', previewColors: ['#0a192f', '#64ffda', '#e63946'] },
    ],
    requiredInputs: [],
    optionalInputs: ['image', 'brand-kit', 'logo'],
    scanStrictness: 'strict',
  },
  architecture: {
    id: 'architecture',
    name: 'Architecture QR',
    description: 'Buildings and cityscapes built from QR geometry',
    icon: 'Building2',
    defaultModel: 'qr-monster-v2',
    promptStrategy: 'template',
    parameterPresets: {
      controlWeight: 0.9,
      guidanceScale: 7,
      strength: 0.85,
      conditioningScale: 1.6,
      numInferenceSteps: 35,
    },
    styleVariations: [
      { id: 'arch-modern', name: 'Modern City', prompt: 'Modern city skyline built from QR code blocks, glass and steel, aerial perspective, golden hour', previewColors: ['#2c3e50', '#3498db', '#ecf0f1'] },
      { id: 'arch-industrial', name: 'Industrial', prompt: 'Industrial factory interior with QR modules as panels and machinery, depth compositing, warm industrial light', previewColors: ['#4a4a4a', '#8b7355', '#c4a882'] },
      { id: 'arch-futuristic', name: 'Futuristic', presetId: 'dark-futuristic', prompt: 'Futuristic cityscape with QR as building facades, holographic overlays, neon grid', previewColors: ['#0a0a0a', '#00d4ff', '#1a1a2e'] },
    ],
    requiredInputs: [],
    optionalInputs: ['image', 'text'],
    scanStrictness: 'moderate',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk QR',
    description: 'Neon-drenched cyber aesthetics with visible QR elements',
    icon: 'Zap',
    defaultModel: 'qr-monster-v2',
    promptStrategy: 'template',
    parameterPresets: {
      controlWeight: 0.8,
      guidanceScale: 9,
      strength: 0.9,
      conditioningScale: 1.4,
      numInferenceSteps: 35,
    },
    styleVariations: [
      { id: 'cyber-neon', name: 'Neon Glow', presetId: 'cyberpunk-neon', prompt: 'Cyberpunk QR with electric neon glow, hot pink and cyan, dark urban backdrop, glitch effects', previewColors: ['#0d0221', '#ff2975', '#00fff5'] },
      { id: 'cyber-android', name: 'Android', prompt: 'Cyberpunk android portrait, QR modules as facial geometry, LED eyes, metallic skin', previewColors: ['#1a1a2e', '#e94560', '#0f3460'] },
      { id: 'cyber-glitch', name: 'Glitch Art', prompt: 'Digital glitch art QR, corrupted pixel blocks, scanline interference, VHS noise', previewColors: ['#000000', '#00ff41', '#ff0090'] },
      { id: 'cyber-holo', name: 'Holographic', prompt: 'Holographic QR projection, iridescent light refractions, floating in dark space', previewColors: ['#0a0a0a', '#a855f7', '#06b6d4'] },
    ],
    requiredInputs: [],
    optionalInputs: ['image', 'text'],
    scanStrictness: 'relaxed',
  },
  abstract: {
    id: 'abstract',
    name: 'Abstract QR',
    description: 'Abstract art, fractals, and geometric patterns',
    icon: 'Shapes',
    defaultModel: 'qr-monster-v2',
    promptStrategy: 'llm-generated',
    parameterPresets: {
      controlWeight: 0.75,
      guidanceScale: 7,
      strength: 0.9,
      conditioningScale: 1.3,
      numInferenceSteps: 35,
    },
    styleVariations: [
      { id: 'abs-geometric', name: 'Geometric', prompt: 'Abstract geometric QR composition, Bauhaus-inspired shapes, primary colors, bold lines', previewColors: ['#e63946', '#457b9d', '#f1faee'] },
      { id: 'abs-watercolor', name: 'Watercolor', prompt: 'Watercolor abstract QR, soft bleeding colors, organic ink flow, paper texture', previewColors: ['#a8d8ea', '#aa96da', '#fcbad3'] },
      { id: 'abs-fractal', name: 'Fractal', prompt: 'Fractal QR pattern, infinite recursive geometry, Mandelbrot-inspired, cosmic colors', previewColors: ['#0d0d0d', '#6c3483', '#1abc9c'] },
      { id: 'abs-mosaic', name: 'Mosaic', prompt: 'Mosaic tile QR art, Mediterranean colors, ceramic texture, grouted modules', previewColors: ['#1e6091', '#d4a373', '#e9c46a'] },
    ],
    requiredInputs: [],
    optionalInputs: ['image', 'brand-kit'],
    scanStrictness: 'moderate',
  },
  isometric: {
    id: 'isometric',
    name: 'Isometric QR',
    description: '3D isometric worlds built on QR grid',
    icon: 'Box',
    defaultModel: 'qr-monster-v2',
    promptStrategy: 'template',
    parameterPresets: {
      controlWeight: 0.9,
      guidanceScale: 7.5,
      strength: 0.85,
      conditioningScale: 1.6,
      numInferenceSteps: 35,
    },
    styleVariations: [
      { id: 'iso-city', name: 'Mini City', prompt: 'Isometric miniature city scene, QR modules as building blocks, tiny cars and trees, tilt-shift', previewColors: ['#2ecc71', '#3498db', '#e74c3c'] },
      { id: 'iso-game', name: 'Game World', prompt: 'Isometric pixel game world, QR as terrain, 8-bit characters, RPG map style', previewColors: ['#44bd32', '#e1b12c', '#c23616'] },
      { id: 'iso-factory', name: 'Factory', prompt: 'Isometric factory interior, QR as conveyor belts and machinery, industrial automation', previewColors: ['#636e72', '#fdcb6e', '#e17055'] },
    ],
    requiredInputs: [],
    optionalInputs: ['text'],
    scanStrictness: 'moderate',
  },
  storytelling: {
    id: 'storytelling',
    name: 'Storytelling QR',
    description: 'Narrative scenes that tell a story with embedded QR',
    icon: 'BookOpen',
    defaultModel: 'qr-monster-v2',
    promptStrategy: 'llm-generated',
    parameterPresets: {
      controlWeight: 0.8,
      guidanceScale: 7,
      strength: 0.88,
      conditioningScale: 1.4,
      numInferenceSteps: 35,
    },
    styleVariations: [
      { id: 'story-adventure', name: 'Adventure', prompt: 'Epic adventure scene with QR woven into the landscape, treasure map style, warm sepia tones', previewColors: ['#8b6914', '#2c1810', '#f5e6d3'] },
      { id: 'story-scifi', name: 'Sci-Fi', prompt: 'Science fiction narrative scene, QR as alien technology or star map, deep space colors', previewColors: ['#0a0a2e', '#00d4ff', '#8b5cf6'] },
      { id: 'story-nature', name: 'Nature', presetId: 'organic-nature', prompt: 'Nature storytelling scene, QR hidden in botanical garden, forest canopy, wildlife details', previewColors: ['#2d5016', '#8fbc5a', '#f4f1de'] },
      { id: 'story-urban', name: 'Urban Life', prompt: 'Urban street scene with QR integrated into graffiti, street art, city textures', previewColors: ['#2d2d2d', '#e63946', '#f1faee'] },
    ],
    requiredInputs: [],
    optionalInputs: ['image', 'text', 'brand-kit'],
    scanStrictness: 'moderate',
  },
}

export function getQrMode(id: QrModeId): QrMode {
  return QR_MODES[id]
}

export function getAllQrModes(): QrMode[] {
  return Object.values(QR_MODES)
}
